ACSEO\Bundle\CalendrierBundle\Entity\Comment:
    type: entity
    table: null
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        authorNickName:
            type: string
            length: 255
        content:
            type: text
        createdAt:
            type: datetime
    manyToOne:
        article:
            targetEntity: ACSEO\Bundle\CalendrierBundle\Entity\Article
            joinColumn:
                name: article_id
                referencedColumnName: id
    lifecycleCallbacks: {  }
