ACSEO\Bundle\CalendrierBundle\Entity\Article:
    Source:
        columns:
            id: ~
            title: ~
            publishedDate: ~
            author: ~
            writer.firstName: ~
            writer.lastName: ~
            writer.companyName: ~
            comments: ~        
        groupBy: ~
        filterable: ~
    Columns:
        id:
            filterable: false
            visible: false
            id: id
            title: id
        title:
            filterable: true
            visible: true
            id: title
            title: Titre de l'article
            operatorsVisible: false
        author:
            filterable: false
            visible: true
            id: author
            title: Auteur
            operatorsVisible: false
        publishedDate:
            filterable: false
            visible: true
            id: publishedDate
            title: Date de publication
        writer.firstName:
            filterable: false
            visible: false
            id: writer.firstName
            field: writer.firstName
            source: true
        writer.lastName:
            filterable: true
            visible: false
            id: writer.lastName
            field: writer.lastName
            source: true
            title: Nom de l'auteur
            operatorsVisible: false
            filter: select
        writer.companyName:
            filterable: true
            visible: true
            id: writer.companyName
            field: writer.companyName
            source: true
            title: Société
            operatorsVisible: false
            filter: select
            selectMulti: true
            selectExpanded: true
            #selectFrom: source
        # comments:
        #     filterable: true
        #     visible: true
        #     id: comments
        #     title: comments
        